server:
  port: 8000
spring:
  datasource:
    username: na_sobes
    password: na_sobes
    url: jdbc:postgresql://localhost:5432/na_sobes
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
    generate-ddl: true

bot:
  name: NaSobesTestBot
  token: 6786036914:AAEfsQTuPNOEce9XSI7CZvm8Wi6mm7wMRps
user:
  notactivedays: 15


