name: deploy-prod
run-name: ${{ github.actor }} is deploy Back to prod
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  deploy-back:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: 'install maven'
        run: sudo apt install maven

      - name: 'build jar file'
        run: mvn package -X

      - name: 'show structure'
        run: ls -al

      - name: 'delete old jar file'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '31.129.99.106'
          username: 'root'
          password: 'pZJAsbwD&2PV'
          port: '22'
          script: |
            cd ../../var/www/back/target
            sudo kill -9 $(sudo lsof -t -i:8000)
            sudo rm -r *

      - name: 'deploy jar file'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: '31.129.99.106'
          username: 'root'
          password: 'pZJAsbwD&2PV'
          port: '22'
          source: 'target/*.jar'
          target: '../../var/www/back'

      - name: 'start-remote-command'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '31.129.99.106'
          username: 'root'
          password: 'pZJAsbwD&2PV'
          port: '22'
          script: |
            cd ../../var/www/back/target
            screen -m -d java -jar CryptoPulse-0.0.1-SNAPSHOT.jar
            ls -al
